<template>
	<div class="loading">
		<div class="loadingio-spinner-double-ring-f6iasjr79lf">
			<div class="ldio-1vm35yeh17w">
				<div></div>
				<div></div>
				<div><div></div></div>
				<div><div></div></div>
			</div>
		</div>
	</div>
</template>

<script>
export default {
	name: "MISALoading",
};
</script>

<style scoped>
@keyframes ldio-1vm35yeh17w {
	0% {
		transform: rotate(0);
	}
	100% {
		transform: rotate(360deg);
	}
}

.loading {
	display: flex;
	align-items: center;
	justify-content: center;
	background: #f1f2f3;
}
.ldio-1vm35yeh17w div {
	box-sizing: border-box !important;
}
.ldio-1vm35yeh17w > div {
	position: absolute;
	width: 144px;
	height: 144px;
	top: 28px;
	left: 28px;
	border-radius: 50%;
	border: 16px solid #000;
	border-color: #93dbe9 transparent #93dbe9 transparent;
	animation: ldio-1vm35yeh17w 1s linear infinite;
}

.ldio-1vm35yeh17w > div:nth-child(2),
.ldio-1vm35yeh17w > div:nth-child(4) {
	width: 108px;
	height: 108px;
	top: 46px;
	left: 46px;
	animation: ldio-1vm35yeh17w 1s linear infinite reverse;
}
.ldio-1vm35yeh17w > div:nth-child(2) {
	border-color: transparent #689cc5 transparent #689cc5;
}
.ldio-1vm35yeh17w > div:nth-child(3) {
	border-color: transparent;
}
.ldio-1vm35yeh17w > div:nth-child(3) div {
	position: absolute;
	width: 100%;
	height: 100%;
	transform: rotate(45deg);
}
.ldio-1vm35yeh17w > div:nth-child(3) div:before,
.ldio-1vm35yeh17w > div:nth-child(3) div:after {
	content: "";
	display: block;
	position: absolute;
	width: 16px;
	height: 16px;
	top: -16px;
	left: 48px;
	background: #93dbe9;
	border-radius: 50%;
	box-shadow: 0 128px 0 0 #93dbe9;
}
.ldio-1vm35yeh17w > div:nth-child(3) div:after {
	left: -16px;
	top: 48px;
	box-shadow: 128px 0 0 0 #93dbe9;
}

.ldio-1vm35yeh17w > div:nth-child(4) {
	border-color: transparent;
}
.ldio-1vm35yeh17w > div:nth-child(4) div {
	position: absolute;
	width: 100%;
	height: 100%;
	transform: rotate(45deg);
}
.ldio-1vm35yeh17w > div:nth-child(4) div:before,
.ldio-1vm35yeh17w > div:nth-child(4) div:after {
	content: "";
	display: block;
	position: absolute;
	width: 16px;
	height: 16px;
	top: -16px;
	left: 30px;
	background: #689cc5;
	border-radius: 50%;
	box-shadow: 0 92px 0 0 #689cc5;
}
.ldio-1vm35yeh17w > div:nth-child(4) div:after {
	left: -16px;
	top: 30px;
	box-shadow: 92px 0 0 0 #689cc5;
}
.loadingio-spinner-double-ring-f6iasjr79lf {
	width: 200px;
	height: 200px;
	display: inline-block;
	overflow: hidden;
}
.ldio-1vm35yeh17w {
	width: 100%;
	height: 100%;
	position: relative;
	transform: translateZ(0) scale(1);
	backface-visibility: hidden;
	transform-origin: 0 0; /* see note above */
}
.ldio-1vm35yeh17w div {
	box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
